In [1]:
df_2023 = pd.read_csv(RAW / "Bookings_2023.csv")
df_2024 = pd.read_csv(RAW / "Bookings_2024.csv")
df_2025 = pd.read_csv(RAW / "Bookings_2025.csv")

print(df_2023.shape, df_2024.shape, df_2025.shape)

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

RAW = Path("../data/raw")

In [ ]:
df = pd.concat([df_2023, df_2024, df_2025], ignore_index=True)

In [ ]:
df.shape

(13927, 12)

In [ ]:
# 1. Remove duplicate bookings
df = df.drop_duplicates(subset="BookingID", keep="first")

# 2. Fix dates
df["BookingDate"] = pd.to_datetime(df["BookingDate"], errors="coerce")
df["TravelStartDate"] = pd.to_datetime(df["TravelStartDate"], errors="coerce")
df["BookingYear"] = df["BookingDate"].dt.year
df["BookingMonth"] = df["BookingDate"].dt.month

# 3. Clean the Status text
df["Status"] = df["Status"].str.strip().str.lower().replace({"canceled": "cancelled"})

# 4. Fill missing values
df["DiscountPctClean"] = df["DiscountPct"].fillna(0)
df["AgentClean"] = df["AgentID"].fillna("Unknown")

In [ ]:
print(df)

           BookingID BookingDate TravelStartDate CustomerID PackageID AgentID  \
0      BK-2023-00001  2023-01-01      2023-02-20     C01696      PK06    AG10
1      BK-2023-00002  2023-01-01      2023-07-07     C01980      PK09    AG02
2      BK-2023-00003  2023-01-01      2023-08-27     C01992      PK15    AG08
3      BK-2023-00004  2023-01-01      2023-03-27     C02537      PK06     NaN
4      BK-2023-00005  2023-01-01      2023-02-08     C03846      PK01     NaN
...              ...         ...             ...        ...       ...     ...
13922  BK-2025-05430  2025-12-31      2026-01-20     C05301      PK02    AG04
13923  BK-2025-05431  2025-12-31      2026-02-10     C05530      PK16    AG11
13924  BK-2025-05432  2025-12-31      2026-03-21     C05655      PK02    AG00
13925  BK-2025-05433  2025-12-31      2026-02-06     C05860      PK06    AG00
13926  BK-2025-05434  2025-12-31      2026-02-09     C06210      PK02    AG03

       Adults  Children  UnitPriceUSD  DiscountPct     Status  PaymentMethod  \
0           2         0          1250         0.00  completed  Bank Transfer
1           1         0          2990         0.00  completed           Card
2           2         3          4485         0.00  completed         PayPal
3           1         0          1250         0.00  completed           Card
4           1         0           420         0.15  completed  Bank Transfer
...       ...       ...           ...          ...        ...            ...
13922       5         0           505         0.05  completed  Bank Transfer
13923       1         0          5290         0.10  completed         M-Pesa
13924       4         0           435         0.05  completed           Card
13925       2         0          1440         0.00  completed         PayPal
13926       2         0           435         0.00  completed  Bank Transfer

       BookingYear  BookingMonth  DiscountPctClean AgentClean
0             2023             1              0.00       AG10
1             2023             1              0.00       AG02
2             2023             1              0.00       AG08
3             2023             1              0.00    Unknown
4             2023             1              0.15    Unknown
...            ...           ...               ...        ...
13922         2025            12              0.05       AG04
13923         2025            12              0.10       AG11
13924         2025            12              0.05       AG00
13925         2025            12              0.00       AG00
13926         2025            12              0.00       AG03

[13890 rows x 16 columns]

In [ ]:
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG10
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,2023,1,0.00,AG02
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,2023,1,0.00,AG08
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,completed,Card,2023,1,0.00,Unknown
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,completed,Bank Transfer,2023,1,0.15,Unknown

In [ ]:
arr = np.array([1, 2, 3, 4], dtype=np.float32)
print(arr)

[1. 2. 3. 4.]

In [ ]:
print(arr.ndim)

1

In [ ]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float32)
print(matrix.shape)

(2, 4)

In [ ]:
print(matrix.size)

8

In [ ]:
zero_arr = np.zeros((3, 4), dtype=np.float32)

In [ ]:
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [ ]:
arr_adults = df_2024["Adults"].to_numpy()
print(arr_adults[:10])

[2 1 5 2 2 2 8 2 2 2]

In [ ]:
data = np.array([10, 20, 30,40])

In [ ]:
print(data)

[10 20 30 40]

In [ ]:
print(data.dtype)

int64

In [ ]:
print(data.shape)

(4,)

In [ ]:
print(data.nbytes)

32

In [ ]:
print(data.ndim)

1

In [ ]:
df.head(5)

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG10
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,2023,1,0.00,AG02
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,2023,1,0.00,AG08
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,completed,Card,2023,1,0.00,Unknown
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,completed,Bank Transfer,2023,1,0.15,Unknown

In [ ]:
children = df_2024["Children"].to_numpy()
print(children[:10])

[1 0 0 1 3 0 0 0 0 0]

In [ ]:
print(children)

[1 0 0 ... 0 1 0]

In [ ]:
Gedion = np.zeros(10)
print(Gedion)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [ ]:
discount = df_2023["DiscountPct"].to_numpy()
print(discount)

[0.   0.   0.   ... 0.1  0.05 0.  ]

In [ ]:
prices = df_2023["UnitPriceUSD"].to_numpy()
print(prices)

[1250 2990 4485 ...  460  650 4710]

In [ ]:
print(data)

[10 20 30 40]

In [ ]:
values_above_30 = data > 30
print(values_above_30)

[False False False  True]

In [ ]:
top_bookings = prices > 10000
print(top_bookings)

[False False False ... False False False]

In [ ]:
Revelation_pack = df_2023[["Adults", "Children"]].to_numpy()
print(Revelation_pack)

[[2 0]
 [1 0]
 [2 3]
 ...
 [9 0]
 [1 0]
 [2 0]]

In [ ]:
print(Revelation_pack.shape)

(3867, 2)

In [ ]:
total_prices = prices.sum()
print(total_prices)

10511475

In [ ]:
Emilio = Revelation_pack.sum(axis=0)
print(Emilio)

[11486  2054]

In [ ]:
sum_Gedion = Revelation_pack.sum()
print(sum_Gedion)

13540

In [ ]:
combined_adults_children = np.concatenate((Revelation_pack[:, 0], Revelation_pack[:, 1]))
print(combined_adults_children)

[2 1 2 ... 0 0 0]

In [ ]:
adults = df_2024["Adults"].to_numpy()
children = df_2024["Children"].to_numpy()

difference = len(adults) - len(children)
print(difference)

0

In [ ]:
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG10
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,2023,1,0.00,AG02
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,2023,1,0.00,AG08
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,completed,Card,2023,1,0.00,Unknown
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,completed,Bank Transfer,2023,1,0.15,Unknown

In [ ]:
df["Travellers"] = df["Adults"] + df["Children"]
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean,Travellers
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG10,2
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,2023,1,0.00,AG02,1
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,2023,1,0.00,AG08,5
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,completed,Card,2023,1,0.00,Unknown,1
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,completed,Bank Transfer,2023,1,0.15,Unknown,1

In [ ]:
df["Grossvalue"] = df["UnitPriceUSD"]
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean,Travellers,Grossvalue
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG10,2,1250
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,2023,1,0.00,AG02,1,2990
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,2023,1,0.00,AG08,5,4485
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,completed,Card,2023,1,0.00,Unknown,1,1250
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,completed,Bank Transfer,2023,1,0.15,Unknown,1,420

In [ ]:
df["Discount"] = df["Grossvalue"] * df["DiscountPctClean"]
df.head(15)

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean,Travellers,Grossvalue,Discount
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG10,2,1250,0.00
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,completed,Card,2023,1,0.00,AG02,1,2990,0.00
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,completed,PayPal,2023,1,0.00,AG08,5,4485,0.00
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,completed,Card,2023,1,0.00,Unknown,1,1250,0.00
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,completed,Bank Transfer,2023,1,0.15,Unknown,1,420,63.00
5,BK-2023-00006,2023-01-01,2023-01-11,C04189,PK02,NaN,2,1,435,0.05,completed,Card,2023,1,0.05,Unknown,3,435,21.75
6,BK-2023-00007,2023-01-01,2023-03-02,C04381,PK05,NaN,7,0,780,0.05,completed,Bank Transfer,2023,1,0.05,Unknown,7,780,39.00
7,BK-2023-00008,2023-01-01,2023-07-13,C04460,PK08,AG04,2,3,1355,0.10,cancelled,PayPal,2023,1,0.10,AG04,5,1355,135.50
8,BK-2023-00009,2023-01-01,2023-01-28,C06138,PK05,AG04,2,0,895,0.00,completed,Card,2023,1,0.00,AG04,2,895,0.00
9,BK-2023-00010,2023-01-01,2023-02-23,C06141,PK09,AG02,2,0,2600,0.00,completed,PayPal,2023,1,0.00,AG02,2,2600,0.00
10,BK-2023-00011,2023-01-02,2023-03-09,C01940,PK11,AG06,9,0,3900,0.00,completed,PayPal,2023,1,0.00,AG06,9,3900,0.00
11,BK-2023-00012,2023-01-02,2023-04-01,C01941,PK06,AG02,1,0,1250,0.00,completed,Bank Transfer,2023,1,0.00,AG02,1,1250,0.00
12,BK-2023-00013,2023-01-02,2023-04-02,C02257,PK06,AG03,2,0,1250,0.00,completed,M-Pesa,2023,1,0.00,AG03,2,1250,0.00
13,BK-2023-00014,2023-01-02,2023-06-24,C02790,PK12,AG02,4,0,4800,0.10,completed,Bank Transfer,2023,1,0.10,AG02,4,4800,480.00
14,BK-2023-00015,2023-01-02,2023-02-18,C03023,PK09,NaN,2,1,2600,0.00,completed,Card,2023,1,0.00,Unknown,3,2600,0.00

In [ ]:
df["NetAmount"] = df["Grossvalue"] - df["Discount"]

print(df[["Grossvalue", "DiscountPctClean", "Discount", "NetAmount"]].head(10))
print(df["DiscountPct"].isna().sum(), "blank discounts were treated as 0")

   Grossvalue  DiscountPctClean  Discount  NetAmount
0        1250              0.00      0.00    1250.00
1        2990              0.00      0.00    2990.00
2        4485              0.00      0.00    4485.00
3        1250              0.00      0.00    1250.00
4         420              0.15     63.00     357.00
5         435              0.05     21.75     413.25
6         780              0.05     39.00     741.00
7        1355              0.10    135.50    1219.50
8         895              0.00      0.00     895.00
9        2600              0.00      0.00    2600.00
417 blank discounts were treated as 0

In [ ]:
df["Grossvalue"] = (df["Adults"] + 0.5 * df["Children"]) * df["UnitPriceUSD"]
df["Discount"] = df["Grossvalue"] * df["DiscountPct"].fillna(0)
df["NetAmount"] = df["Grossvalue"] - df["Discount"]

df[["BookingID", "Grossvalue", "Discount", "NetAmount"]].tail(20)

           BookingID  Grossvalue  Discount  NetAmount
13907  BK-2025-05415     25920.0     0.000  25920.000
13908  BK-2025-05416     15697.5     0.000  15697.500
13909  BK-2025-05417     34375.0  1718.750  32656.250
13910  BK-2025-05418     10840.0     0.000  10840.000
13911  BK-2025-05419      1010.0     0.000   1010.000
13912  BK-2025-05420      4742.5   711.375   4031.125
13913  BK-2025-05421     13750.0     0.000  13750.000
13914  BK-2025-05422     16400.0     0.000  16400.000
13915  BK-2025-05423     42780.0     0.000  42780.000
13916  BK-2025-05424     17187.5     0.000  17187.500
13917  BK-2025-05425      2425.0   121.250   2303.750
13918  BK-2025-05426      2880.0   144.000   2736.000
13919  BK-2025-05427     26910.0  2691.000  24219.000
13920  BK-2025-05428     14905.0     0.000  14905.000
13921  BK-2025-05429     25400.0  2540.000  22860.000
13922  BK-2025-05430      2525.0   126.250   2398.750
13923  BK-2025-05431      5290.0   529.000   4761.000
13924  BK-2025-05432      1740.0    87.000   1653.000
13925  BK-2025-05433      2880.0     0.000   2880.000
13926  BK-2025-05434       870.0     0.000    870.000

In [ ]:
df["NetAmount"] = df["Grossvalue"] - df["Discount"]
df.tail(20)

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,Status,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean,Travellers,Grossvalue,Discount,NetAmount
13907,BK-2025-05415,2025-12-30,2026-07-11,C02648,PK17,AG00,2,0,12960,0.00,confirmed,PayPal,2025,12,0.00,AG00,2,25920.0,0.000,25920.000
13908,BK-2025-05416,2025-12-30,2026-02-18,C02964,PK15,AG02,2,3,4485,0.00,completed,Card,2025,12,0.00,AG02,5,15697.5,0.000,15697.500
13909,BK-2025-05417,2025-12-30,2026-08-01,C03057,PK18,AG09,5,0,6875,0.05,confirmed,Bank Transfer,2025,12,0.05,AG09,5,34375.0,1718.750,32656.250
13910,BK-2025-05418,2025-12-30,2026-07-30,C03289,PK14,AG00,2,0,5420,0.00,cancelled,Card,2025,12,0.00,AG00,2,10840.0,0.000,10840.000
13911,BK-2025-05419,2025-12-30,2026-01-30,C03474,PK02,AG00,2,0,505,0.00,completed,Bank Transfer,2025,12,0.00,AG00,2,1010.0,0.000,1010.000
13912,BK-2025-05420,2025-12-30,2026-03-03,C03973,PK08,AG06,2,3,1355,0.15,completed,Bank Transfer,2025,12,0.15,AG06,5,4742.5,711.375,4031.125
13913,BK-2025-05421,2025-12-30,2026-07-25,C05382,PK18,AG00,2,0,6875,0.00,confirmed,PayPal,2025,12,0.00,AG00,2,13750.0,0.000,13750.000
13914,BK-2025-05422,2025-12-30,2026-01-13,C05517,PK13,AG00,2,0,8200,0.00,completed,Bank Transfer,2025,12,0.00,AG00,2,16400.0,0.000,16400.000
13915,BK-2025-05423,2025-12-30,2026-04-15,C05669,PK13,AG12,6,0,7130,0.00,completed,M-Pesa,2025,12,0.00,AG12,6,42780.0,0.000,42780.000
13916,BK-2025-05424,2025-12-31,2026-09-18,C00517,PK18,AG04,2,1,6875,0.00,confirmed,M-Pesa,2025,12,0.00,AG04,3,17187.5,0.000,17187.500
13917,BK-2025-05425,2025-12-31,2026-02-03,C00909,PK01,AG03,5,0,485,0.05,completed,Card,2025,12,0.05,AG03,5,2425.0,121.250,2303.750
13918,BK-2025-05426,2025-12-31,2026-02-20,C02490,PK06,AG00,2,0,1440,0.05,completed,Card,2025,12,0.05,AG00,2,2880.0,144.000,2736.000
13919,BK-2025-05427,2025-12-31,2026-05-05,C03716,PK11,AG02,6,0,4485,0.10,cancelled,Card,2025,12,0.10,AG02,6,26910.0,2691.000,24219.000
13920,BK-2025-05428,2025-12-31,2026-02-03,C04589,PK08,AG12,11,0,1355,0.00,cancelled,Card,2025,12,0.00,AG12,11,14905.0,0.000,14905.000
13921,BK-2025-05429,2025-12-31,2026-07-23,C04917,PK12,AG00,4,0,6350,0.10,confirmed,Bank Transfer,2025,12,0.10,AG00,4,25400.0,2540.000,22860.000
13922,BK-2025-05430,2025-12-31,2026-01-20,C05301,PK02,AG04,5,0,505,0.05,completed,Bank Transfer,2025,12,0.05,AG04,5,2525.0,126.250,2398.750
13923,BK-2025-05431,2025-12-31,2026-02-10,C05530,PK16,AG11,1,0,5290,0.10,completed,M-Pesa,2025,12,0.10,AG11,1,5290.0,529.000,4761.000
13924,BK-2025-05432,2025-12-31,2026-03-21,C05655,PK02,AG00,4,0,435,0.05,completed,Card,2025,12,0.05,AG00,4,1740.0,87.000,1653.000
13925,BK-2025-05433,2025-12-31,2026-02-06,C05860,PK06,AG00,2,0,1440,0.00,completed,PayPal,2025,12,0.00,AG00,2,2880.0,0.000,2880.000
13926,BK-2025-05434,2025-12-31,2026-02-09,C06210,PK02,AG03,2,0,435,0.00,completed,Bank Transfer,2025,12,0.00,AG03,2,870.0,0.000,870.000

In [ ]:
df["BookingCategory"] = np.where(
    df["Travellers"] == 4,
     "Large",
      "Small")


df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,...,PaymentMethod,BookingYear,BookingMonth,DiscountPctClean,AgentClean,Travellers,Grossvalue,Discount,NetAmount,BookingCategory
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,...,Bank Transfer,2023,1,0.00,AG10,2,2500.0,0.0,2500.0,Small
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,...,Card,2023,1,0.00,AG02,1,2990.0,0.0,2990.0,Small
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,...,PayPal,2023,1,0.00,AG08,5,15697.5,0.0,15697.5,Small
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,...,Card,2023,1,0.00,Unknown,1,1250.0,0.0,1250.0,Small
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,...,Bank Transfer,2023,1,0.15,Unknown,1,420.0,63.0,357.0,Small

In [ ]:
import numpy as np

conditions = [
    df["NetAmount"] < 2000,
    df["NetAmount"] < 5000,
    df["NetAmount"] < 10000,
]

choices = ["Small", "Medium", "Large"]

df["BookingSize"] = np.select(conditions, choices, default="Premium")

df["BookingSize"].value_counts()
df.head()

,BookingID,BookingDate,TravelStartDate,CustomerID,PackageID,AgentID,Adults,Children,UnitPriceUSD,DiscountPct,...,BookingYear,BookingMonth,DiscountPctClean,AgentClean,Travellers,Grossvalue,Discount,NetAmount,BookingCategory,BookingSize
0,BK-2023-00001,2023-01-01,2023-02-20,C01696,PK06,AG10,2,0,1250,0.00,...,2023,1,0.00,AG10,2,2500.0,0.0,2500.0,Small,Medium
1,BK-2023-00002,2023-01-01,2023-07-07,C01980,PK09,AG02,1,0,2990,0.00,...,2023,1,0.00,AG02,1,2990.0,0.0,2990.0,Small,Medium
2,BK-2023-00003,2023-01-01,2023-08-27,C01992,PK15,AG08,2,3,4485,0.00,...,2023,1,0.00,AG08,5,15697.5,0.0,15697.5,Small,Premium
3,BK-2023-00004,2023-01-01,2023-03-27,C02537,PK06,NaN,1,0,1250,0.00,...,2023,1,0.00,Unknown,1,1250.0,0.0,1250.0,Small,Small
4,BK-2023-00005,2023-01-01,2023-02-08,C03846,PK01,NaN,1,0,420,0.15,...,2023,1,0.15,Unknown,1,420.0,63.0,357.0,Small,Small

In [ ]:
df["BookingDate"] = pd.to_datetime(df["BookingDate"])
df["Status"] = df["Status"].str.strip().str.title().replace({"Canceled": "Cancelled"})

live = df[df["Status"] != "Cancelled"].copy()
live["Year"] = live["BookingDate"].dt.year

yearly = live.groupby("Year").agg(
    Bookings=("BookingID", "count"),
    Revenue=("NetAmount", "sum"),
    Customers=("CustomerID", "nunique"),
)
yearly["AvgBooking"] = yearly["Revenue"] / yearly["Bookings"]
yearly["Revenue_Growth_%"] = (yearly["Revenue"].pct_change() * 100).round(1)
yearly["Bookings_Growth_%"] = (yearly["Bookings"].pct_change() * 100).round(1)

yearly.round(0)

,Bookings,Revenue,Customers,AvgBooking,Revenue_Growth_%,Bookings_Growth_%
Year,,,,,,
2023,3507,29800966.0,2735,8498.0,NaN,NaN
2024,4170,39694231.0,3049,9519.0,33.0,19.0
2025,4901,53358318.0,3463,10887.0,34.0,18.0

In [ ]:
df["BookingDate"] = pd.to_datetime(df["BookingDate"])
df["BookingYear"] = df["BookingDate"].dt.year

df["Travellers"] = df["Adults"] + df["Children"]
df["Grossvalue"] = (df["Adults"] + 0.5 * df["Children"]) * df["UnitPriceUSD"]
df["NetValue"] = df["Grossvalue"] * (1 - df["DiscountPct"].fillna(0))

df["Status"] = df["Status"].str.strip().str.title().replace({"Canceled": "Cancelled"})
live = df[df["Status"] != "Cancelled"]

In [ ]:
BusinessGrowth = (
    live.groupby("BookingYear").agg(
        TotalNetValues=("NetValue", "sum"),
        Travellers_served=("Travellers", "sum"),
        Bookings_made=("BookingID", "nunique"),
    )
    .reset_index()
)

BusinessGrowth["Revenue_Growth_%"] = (BusinessGrowth["TotalNetValues"].pct_change() * 100).round(1)
BusinessGrowth

,BookingYear,TotalNetValues,Travellers_served,Bookings_made,Revenue_Growth_%
0,2023,2.980097e+07,12333,3507,NaN
1,2024,3.969423e+07,14473,4170,33.2
2,2025,5.335832e+07,17133,4901,34.4

In [ ]:
print(live.columns.tolist())
print(packages.columns.tolist())

['BookingID', 'BookingDate', 'TravelStartDate', 'CustomerID', 'PackageID', 'AgentID', 'Adults', 'Children', 'UnitPriceUSD', 'DiscountPct', 'Status', 'PaymentMethod', 'BookingYear', 'BookingMonth', 'DiscountPctClean', 'AgentClean', 'Travellers', 'Grossvalue', 'Discount', 'NetAmount', 'BookingCategory', 'BookingSize', 'NetValue']

NameError: name 'packages' is not defined

In [ ]:
live = df[df["Status"] != "Cancelled"].copy()
live["AgentID"] = live["AgentID"].fillna("AG00")

live = live.merge(packages, on="PackageID", how="left")
live = live.merge(agents[["AgentID", "CommissionPct"]], on="AgentID", how="left")

live["Cost"] = live["Travellers"] * live["CostPerPaxUSD"]
live["Commission"] = live["NetValue"] * live["CommissionPct"]
live["GrossProfit"] = live["NetValue"] - live["Cost"] - live["Commission"]

print(len(live))                          # 12,578
print(live["PackageName"].isna().sum())   # 0

NameError: name 'packages' is not defined

In [ ]:
live = df[df["Status"] != "Cancelled"].copy()
live["AgentID"] = live["AgentID"].fillna("AG00")

live = live.merge(packages, on="PackageID", how="left")
live = live.merge(agents[["AgentID", "AgentName", "Channel", "CommissionPct"]], on="AgentID", how="left")

live["GrossProfit"] = (live["NetValue"]
                       - live["Travellers"] * live["CostPerPaxUSD"]
                       - live["NetValue"] * live["CommissionPct"])

package_perf = (
    live.groupby(["PackageID", "PackageName"]).agg(
        Bookings=("BookingID", "nunique"),
        Revenue=("NetValue", "sum"),
        Profit=("GrossProfit", "sum"),
    ).reset_index()
)
package_perf["Margin_%"] = (package_perf["Profit"] / package_perf["Revenue"] * 100).round(1)

print(len(live))

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

RAW = Path("../data/raw")

# 1. load and combine the three booking files
df_2023 = pd.read_csv(RAW / "Bookings_2023.csv")
df_2024 = pd.read_csv(RAW / "Bookings_2024.csv")
df_2025 = pd.read_csv(RAW / "Bookings_2025.csv")
df = pd.concat([df_2023, df_2024, df_2025], ignore_index=True)
print(df.shape)                                   # (13927, 12)

# 2. clean: duplicates, status spellings, dates
df = df.drop_duplicates(subset="BookingID", keep="first")
df["Status"] = df["Status"].str.strip().str.title().replace({"Canceled": "Cancelled"})
df["BookingDate"] = pd.to_datetime(df["BookingDate"])
df["BookingYear"] = df["BookingDate"].dt.year

# 3. calculated columns
df["Travellers"] = df["Adults"] + df["Children"]
df["Grossvalue"] = (df["Adults"] + 0.5 * df["Children"]) * df["UnitPriceUSD"]
df["Discount"] = df["Grossvalue"] * df["DiscountPct"].fillna(0)
df["NetValue"] = df["Grossvalue"] - df["Discount"]
print(df.shape)                                   # (13890, 17)

# 4. load the lookup tables
packages = pd.read_csv(RAW / "Packages.csv")
agents = pd.read_csv(RAW / "Agents.csv")

(13927, 12)
(13890, 17)

FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\raw\\Packages.csv'

In [ ]:
print(sorted(p.name for p in RAW.iterdir()))

['Bookings_2023.csv', 'Bookings_2024.csv', 'Bookings_2025.csv']

In [ ]:
print(packages.shape, agents.shape)     # (18, 8) and (14, 5)

NameError: name 'packages' is not defined

In [ ]:
packages = pd.read_csv(r"C:\Users\USER\Desktop\Data\Packages.csv")
agents = pd.read_csv(r"C:\Users\USER\Desktop\Data\Agents.csv")

In [ ]:
live = df[df["Status"] != "Cancelled"].copy()
live["AgentID"] = live["AgentID"].fillna("AG00")

live = live.merge(packages, on="PackageID", how="left")
live = live.merge(agents[["AgentID", "AgentName", "Channel", "CommissionPct"]], on="AgentID", how="left")

live["GrossProfit"] = (live["NetValue"]
                       - live["Travellers"] * live["CostPerPaxUSD"]
                       - live["NetValue"] * live["CommissionPct"])

package_perf = (
    live.groupby(["PackageID", "PackageName"]).agg(
        Bookings=("BookingID", "nunique"),
        Revenue=("NetValue", "sum"),
        Profit=("GrossProfit", "sum"),
    ).reset_index()
)
package_perf["Margin_%"] = (package_perf["Profit"] / package_perf["Revenue"] * 100).round(1)

print(len(live))     # 12,578

12578

In [ ]:
best_packages = package_perf.merge(
    packages[["PackageID", "Category", "DurationDays", "BasePriceUSD"]],
    on="PackageID", how="left"
)
best_packages = best_packages.sort_values("Revenue", ascending=False).reset_index(drop=True)

top3 = best_packages.head(3)
top3.round(1)

,PackageID,PackageName,Bookings,Revenue,Profit,Margin_%,Category,DurationDays,BasePriceUSD
0,PK12,Mara Great Migration Luxury Camp,992,17106935.4,6323336.7,37.0,Luxury,5,4800
1,PK13,Serengeti Migration Fly-In,746,16798472.8,6130124.5,36.5,Luxury,6,6200
2,PK17,Ultimate East Africa Honeymoon,393,13976124.0,4834052.1,34.6,Luxury,12,9800

In [ ]:
adult_value = (live["Adults"] * live["UnitPriceUSD"]).sum()
child_value = (0.5 * live["Children"] * live["UnitPriceUSD"]).sum()
gross = live["Grossvalue"].sum()
discount = live["Discount"].sum()
net = live["NetValue"].sum()

components = pd.DataFrame({
    "Component": ["Adults", "Children (half price)", "Gross value", "Discounts", "Net value"],
    "USD": [adult_value, child_value, gross, -discount, net],
})
components["Share_of_gross_%"] = (components["USD"] / gross * 100).round(1)
components.round(1)

               Component          USD  Share_of_gross_%
0                 Adults  118365940.0              91.9
1  Children (half price)   10373032.5               8.1
2            Gross value  128738972.5             100.0
3              Discounts   -5885457.4              -4.6
4              Net value  122853515.1              95.4

In [ ]:
by_category = live.groupby("Category").agg(
    Bookings=("BookingID", "nunique"),
    NetValue=("NetValue", "sum"),
).reset_index()
by_category["Share_%"] = (by_category["NetValue"] / by_category["NetValue"].sum() * 100).round(1)
by_category.sort_values("NetValue", ascending=False)

    Category  Bookings      NetValue  Share_%
1     Luxury      4398  8.605076e+07     70.0
2  Mid-Range      4371  2.999431e+07     24.4
0     Budget      3809  6.808444e+06      5.5

In [ ]:
by_channel = live.groupby("Channel").agg(
    Bookings=("BookingID", "nunique"),
    NetValue=("NetValue", "sum"),
).reset_index()
by_channel["Share_%"] = (by_channel["NetValue"] / by_channel["NetValue"].sum() * 100).round(1)
by_channel.sort_values("NetValue", ascending=False)

         Channel  Bookings      NetValue  Share_%
1         Direct      4836  4.426231e+07     36.0
3  Tour Operator      3725  3.360318e+07     27.4
2            OTA      3397  3.013852e+07     24.5
0      Corporate       620  1.484951e+07     12.1

In [ ]:
cats = sorted(live["Category"].unique())
years = sorted(live["BookingYear"].unique())

totals = (live.groupby(["Category", "BookingYear"])["NetValue"]
          .sum().sort_index().to_numpy())             # flat array of 9 numbers

grid = totals.reshape(len(cats), len(years))          # 3 rows x 3 columns
print(grid.shape)                                      # (3, 3)

pivot_np = pd.DataFrame(grid, index=cats, columns=years)
pivot_np.index.name = "Category"
pivot_np["Total"] = grid.sum(axis=1)
pivot_np.round(0)

(3, 3)

                 2023        2024        2025       Total
Category
Budget      1988645.0   2215565.0   2604233.0   6808444.0
Luxury     19050554.0  27199808.0  39800394.0  86050757.0
Mid-Range   8761767.0  10278857.0  10953691.0  29994315.0

In [ ]:
pivot_pd = pd.pivot_table(live, index="Category", columns="BookingYear",
                          values="NetValue", aggfunc="sum")

print(np.allclose(pivot_np[years].to_numpy(), pivot_pd.to_numpy()))   # True

True

In [ ]:
from pathlib import Path

OUT = Path("../data/processed")
OUT.mkdir(parents=True, exist_ok=True)

best_packages.to_csv(OUT / "package_performance.csv", index=False)
top3.to_csv(OUT / "top3_packages.csv", index=False)
components.to_csv(OUT / "value_components.csv", index=False)
by_category.to_csv(OUT / "value_by_category.csv", index=False)
by_channel.to_csv(OUT / "value_by_channel.csv", index=False)
pivot_np.to_csv(OUT / "category_year_pivot.csv", index_label="Category")

# confirm the files were written correctly
for f in sorted(OUT.glob("*.csv")):
    print(f.name, pd.read_csv(f).shape)

category_year_pivot.csv (3, 5)
package_performance.csv (18, 9)
top3_packages.csv (3, 9)
value_by_category.csv (3, 4)
value_by_channel.csv (4, 4)
value_components.csv (5, 3)

In [ ]:
df = pd.concat([pd.read_csv(RAW / f"Bookings_{y}.csv") for y in (2023, 2024, 2025)], ignore_index=True)

df = df.drop_duplicates(subset="BookingID", keep="first")
df["Status"] = df["Status"].str.strip().str.title().replace({"Canceled": "Cancelled"})
df["AgentID"] = df["AgentID"].fillna("AG00")
df["DiscountPct"] = df["DiscountPct"].fillna(0)

df["BookingDate"] = pd.to_datetime(df["BookingDate"])
df["TravelStartDate"] = pd.to_datetime(df["TravelStartDate"])
df["BookingYear"] = df["BookingDate"].dt.year
df["BookingMonth"] = df["BookingDate"].dt.to_period("M").astype(str)

df = df.merge(packages[["PackageID", "PackageName", "Category", "DurationDays", "PrimaryParkID", "CostPerPaxUSD"]],
              on="PackageID", how="left")
df = df.merge(agents[["AgentID", "AgentName", "Channel", "CommissionPct"]], on="AgentID", how="left")

df["Travellers"] = df["Adults"] + df["Children"]
df["Grossvalue"] = (df["Adults"] + 0.5 * df["Children"]) * df["UnitPriceUSD"]
df["Discount"] = df["Grossvalue"] * df["DiscountPct"]
df["NetValue"] = df["Grossvalue"] - df["Discount"]
df["Cost"] = df["Travellers"] * df["CostPerPaxUSD"]
df["Commission"] = df["NetValue"] * df["CommissionPct"]
df["GrossProfit"] = df["NetValue"] - df["Cost"] - df["Commission"]
df["IsActive"] = (df["Status"] != "Cancelled").astype(int)

final_cols = ["BookingID", "BookingDate", "BookingYear", "BookingMonth", "TravelStartDate", "CustomerID",
              "PackageID", "PackageName", "Category", "DurationDays", "PrimaryParkID", "AgentID", "AgentName",
              "Channel", "Adults", "Children", "Travellers", "UnitPriceUSD", "DiscountPct", "Grossvalue",
              "Discount", "NetValue", "CostPerPaxUSD", "Cost", "CommissionPct", "Commission", "GrossProfit",
              "Status", "IsActive", "PaymentMethod"]

final = df[final_cols].sort_values(["BookingDate", "BookingID"]).reset_index(drop=True)

OUT = Path("../data/processed")
OUT.mkdir(parents=True, exist_ok=True)
final.to_csv(OUT / "Bookings_clean_combined.csv", index=False)

In [ ]:
check = pd.read_csv(OUT / "Bookings_clean_combined.csv")
print(check.shape)                                 # (13890, 30)
print(check.isnull().sum().sum())                  # 0
active_2025 = check[(check["BookingYear"] == 2025) & (check["IsActive"] == 1)]
print(round(active_2025["NetValue"].sum(), 2))     # 53358318.5

(13890, 30)
0
53358318.5

In [ ]:
final.to_csv(r"C:\Users\USER\Desktop\Bookings_clean_combined.csv", index=False)